### ISSUE TITLE
crane fails to install on TRAVIS-CI using rakudobrew and panda

### ISSUE THREAD

**Issue by MARTIMM** [atweiden/crane#2]
The following dump shows that some tests fail
```
==> Config::TOML depends on Crane
==> Fetching Crane
==> Building Crane
==> Testing Crane
t/exported-subroutines/at.t .. ok

    # Failed test 'Is expected value'
    # at t/exported-subroutines/in.t line 42
    # expected: 'five'
    #      got: (Any)

    # Failed test 'Is expected value'
    # at t/exported-subroutines/in.t line 43
    # expected: 'five again'
    #      got: (Any)

    # Failed test 'Is expected value'
    # at t/exported-subroutines/in.t line 47
    # expected: '9999999'
    #      got: (Any)

    # Looks like you failed 3 tests of 17

# Failed test at t/exported-subroutines/in.t line 10
# Looks like you failed 1 test of 1
t/exported-subroutines/in.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

t/methods/add.t .............. ok

etcetera
```

This will then not be installed after which the depending modules also fail

Regards
Marcel

**Comment by atweiden** [comment]
Sorry about taking so long on this. I don't get email notifications for new GitHub issues, which is bothersome. I've been working on [Finn](https://github.com/atweiden/finn) which will use Config::TOML and thus Crane, but it wasn't until recently that I reinstalled Config::TOML to find this test failure.

Fixed in https://github.com/atweiden/crane/commit/03a514af2b884b8ff7834926f09cf4c6a4291c6a
